---
title: "02.1_DINS"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## 0 set up: load libraries, custom functions, set defaults
```{r}
# load libraries
# packages we'll be using
packs <- c('tidyverse'        # a must have!
           , 'tidylog'        # makes things very verbose for 2x checking 
           , 'magrittr'       # all of the pipes
           , 'janitor'        # cleans things up
           , 'sf'             # simple features
           , 'mapview'        # quick webmaps for zoom/pan viz
           #'tidycensus',     # access to Census data in a tidy way 
           #'party',          # random forests
           , 'tictoc'         # times things
           , 'beepr'          # makes noises
           , 'psych'          # describe is very useful for descriptive statistics
           , 'sjPlot')        # useful plotting and regression support

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

lapply(packs, library, character.only = TRUE)


# changing from tidyr v0.8.3 -> v1.0.0 broke things for nest and unnest!
# https://tidyr.tidyverse.org/articles/in-packages.html#tidyr-v0-8-3---v1-0-0
library(tidyr)
nest <- nest_legacy                     # Why Hadley, WHY!
unnest <- unnest_legacy


# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
names(.) %>% as.character(.)       # my simple features
}

see_sf() -> sf_in_memory

## what are the spatial references of those SF classes?
mget(sf_in_memory) %>%
purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()

# NOT IN
`%nin%` <- Negate(`%in%`) # custom function

# where are we?
list.files()
list.files('data')

# parameter to keep in general, for later..
pxl_to_ft_conversion <- 0.75
# pxl_to_ft_conversion <- 0.2286004572

set.seed(19870630)

## Make a 'figures' subdirectory if one doesn't exist
# ifelse(!dir.exists(file.path('figures')), dir.create(file.path('figures')), FALSE)
```


## 1 bring in DINS data
```{r}
# GIS DATA from MIRANDA this will be the base from now on (August, 2020)
st_layers(paste0(getwd(), '/data/Outgoing_BuildingSumms_DHL20200423.gdb'))

#create DINS
dins <- read_sf(dsn = paste0(getwd(), '/data/Outgoing_BuildingSumms_DHL20200423.gdb'),
                      layer = 'Buildings_ParcelID_DINS',
                      quiet = FALSE)

```


## 2 explore DINS
```{r}

# Past Syphard et al papers had roof, exterior, window pane, window frame
# More recent ones include wider range of information in DINS

dins %>% 
  st_drop_geometry() %>% names()

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% View()

#Variables to include
#reclass unknowns or blanks to NA
#1. EXTERIORSI exterior siding materials 
#2. FENCEATTAC fence materials 
#3. DECKPORCHO deck/porch materials  
#4  DECKPORCHE deck/porch materials 
#5. ROOFCONSTR roof materials
#6. PATIOCOVER patio/cover materials  
#7. PROPANETAN propane tank distance #reclass others are in order,  
#8. WINDOWPANE window panes #reclass  
#9. VEGCLEARAN vegetation clearance #VEGCLEARAN #reclass missing to Unknown, put in order
#10.EAVES      eaves, has data for ~33% only. 
#11.VENTSCREEN vents - 


#1
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_EXTERIORSI) #exterior siding, have data for 75% of sample; categories ok

#2
dins %>%
st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% 
   tabyl(Buildings_ParcelID_DINS_intersects_FENCEATTAC) #fence materials, have data for 70% of sample, although 50% had no fence; #reclass no fence to N/A

#3
#DECKPORCHO is a deck that is on grade 
dins %>% 
 st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
 tabyl(Buildings_ParcelID_DINS_intersects_DECKPORCHO) #deck and porch --ongrade
#change 'no deck/porch' to N/A 

#4
# DECKPORCHE is a deck that is elevated off the ground
dins %>% 
 st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
 tabyl(Buildings_ParcelID_DINS_intersects_DECKPORCHE) #deck and porch --not sure what E is vs O  
#change 'no deck/porch' to N/A 

#5
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_ROOFCONSTR) #roof, have data for 65% sample, should drop 'other' bc only 18 observations?

#6
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% 
  tabyl(Buildings_ParcelID_DINS_intersects_PATIOCOVER) # materials on covered patio or carport, have data for 65% of sample although
 #44% have no carport or patio cover; reclass 'no' to N/A

#7 
dins %>% 
 st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_PROPANETAN) #propane tank, has data for 56% of sample; #reclass categories so blank is
#unknown and others are in order, N/A = no   tank


#8
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_WINDOWPANE) #windowpane, have data for 40% of sample, categories ok
#reclass No windows to NA

#9
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_VEGCLEARAN)

#10
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
   tabyl(Buildings_ParcelID_DINS_intersects_EAVES) #eaves, has data for ~33% only. change no eaves to NA

#11
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
   tabyl(Buildings_ParcelID_DINS_intersects_VENTSCREEN) #only data on 29% of sample, and 11% of sample had no vents. 
#No Vents needs to be NA
 

#exploring cross walk - if you have unk for exterior siding, you do know carport sometimes and vice versa
  dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_EXTERIORSI,Buildings_ParcelID_DINS_intersects_PATIOCOVER) %>% adorn_totals()

#exploring cross walk 
# DECKPORCHE is a deck that is elevated off the ground
# DECKPORCHO is a deck that is on grade 
#there are some cases where information was entered for both, indicating that part of a deck was elevated and part on grade?

  dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_DECKPORCHE,Buildings_ParcelID_DINS_intersects_DECKPORCHO) %>% adorn_totals()
  
  

#defensive action-Drop
  #drop this one - email from Steve Hawks CALFIRE on 11/2/21 said the blanks are maybe unknown maybe nos, and that the field was new
  #for Woolsey
  dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_DEFENSIVEA)

#UTILITYMIS-Drop
# distance to a utility or misc structure that is over 120 s q. ft.  This is the threshold where a building permit is required.  It
# also is currently the sq. ft. thresholds for the California Building Code Chapter 7A where certain standards apply.  If there are mor
# than one qualifying utility/misc structure, it is the distance to the one that is the closest.  
# don't know what to do with blank fields, even after Steve Hawks email. Drop
dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_UTILITYMIS)


```
## 3 reclass DINS
```{r}
 
dins %>% 
  st_drop_geometry() %>% names()

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% View()

#for random forest blank and unknown need to be NA; when no fence etc, can remain a character 
subdins<-dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  filter(!(ID_Build==4681)) %>% #removed this off investig below, is three mobile homes w diff features assigned to same point
  filter(!(ID_Build==5543)) %>% #removed this off investig below, is three mobile homes w diff features assigned to same point
  tidylog::select(ID_Build,
                  build_EXTERIORSI = Buildings_ParcelID_DINS_intersects_EXTERIORSI,
                  build_FENCEATTAC = Buildings_ParcelID_DINS_intersects_FENCEATTAC, 
                  build_DECKPORCHO = Buildings_ParcelID_DINS_intersects_DECKPORCHO,
                  build_DECKPORCHE = Buildings_ParcelID_DINS_intersects_DECKPORCHE,
                  build_ROOFCONSTR = Buildings_ParcelID_DINS_intersects_ROOFCONSTR,
                  build_PATIOCOVER = Buildings_ParcelID_DINS_intersects_PATIOCOVER,
                  build_PROPANETAN = Buildings_ParcelID_DINS_intersects_PROPANETAN,
                  build_WINDOWPANE = Buildings_ParcelID_DINS_intersects_WINDOWPANE,
                  build_VEGCLEARAN = Buildings_ParcelID_DINS_intersects_VEGCLEARAN,
                  build_EAVES = Buildings_ParcelID_DINS_intersects_EAVES,
                  build_VENTSCREEN = Buildings_ParcelID_DINS_intersects_VENTSCREEN) %>% 
  mutate_at(vars(c(2:12)), list(~ ifelse( . == "Unknown", NA, .)))%>% #if unknown, make missing or NA
  mutate_at(vars(c(2:12)), list(~ ifelse( . == " ", NA, .)))%>%  #if blank, make missing or NA
  mutate_at(vars(c(2:12)), list(~ ifelse( . == "N/A", "None", .)))%>% #if not applicable, turn into 'none'
  mutate(build_PROPANETAN =as.factor(case_when(
                     build_PROPANETAN == "0-10" ~ "1. 0-10",
                     build_PROPANETAN == "11-20" ~ "2. 11-20",
                     build_PROPANETAN == "21-30" ~ "3. 21-30",
                     build_PROPANETAN == ">30'" ~ "4.>30")))%>% 
mutate(build_VEGCLEARAN =as.factor(case_when(
                     build_VEGCLEARAN == "0-30'" ~ "1. 0-30",
                     build_VEGCLEARAN == "30-100'" ~ "2. 30-100",
                     build_VEGCLEARAN == ">100'" ~ "3. >100"))) %>%
  mutate(build_DINS=1)%>% #create a variable to say had a record in DINS
unique() #at this point keeping only unique based on ID build does not remove any data, just deletes repeated lines

#looking at duplicate data; appears that for two ID_Build (4681,5543) there are duplicated and conflicting data; delete these obs
#for all other dupes, the data are the same, so we should just delete repeats
# # length(unique(subdins$ID_Build))
# test<-subset(subdins,duplicated(subdins$ID_Build))
# View(test)
# length(unique(test$ID_Build))
# test2<-subset(test,duplicated(test$ID_Build))

table(subdins$build_PROPANETAN)  
table(subdins$build_VEGCLEARAN)  
```



## 4 merge DINS with full data set & write
```{r}
 
#need to merge with DINS
build <- read_csv(paste0(getwd(), '/output_data/building_2021-10-05.csv')) %>% glimpse 

build %<>% 
  left_join(., subdins, by = c('ID_Build' = 'ID_Build'))

build %>% 
  write_csv(., paste0(getwd(), '/output_data/building_', Sys.Date(), '.csv'))#building_2021-11-03.csv'

```


```{r, citations}
lapply(packages, citation)
```


Last knit on `r format(Sys.time())`


```{r}
system.time(save.image(file = paste0('saved_sessions/wui_r_DINS_',
                                     gsub('[[:punct:]]', '-', Sys.time()), '.RData')))
```

