---
title: "03_distance_to_veg"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# get building distance to shrub
# get building distance to tree
# make a distance raster (shrub, repeat for tree)
# make very small buffer around buildings (like one pixel)
# zonal to get the min distance to veg


## 0 set up
```{r}
# load libraries
# packages we'll be using
packs <- c('tidyverse',      # a must have!
           'tidylog',        # makes things very verbose for 2x checking 
           'magrittr',       # all of the pipes
           'sf',             # simple features
           'stars',          # faster raster
           'raster',         # raster
           # 'rgdal',          # for gdal
           # 'gdalUtils',      # more gdal support
           'tictoc',         # you speed freak
           #'doParallel',     # for parallelizing
           'mapview'         # quick webmaps for zoom/pan viz
           )         

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))
}

lapply(packs, library, character.only = TRUE)


# DONUTS https://github.com/r-spatial/sf/issues/346
st_erase <- function(x, y) st_difference(x, st_union(st_combine(y)))
# st_erase(x,y) will erase y from x.

# for parallelization
library(rstudioapi)
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() >= "4.0.0") {
    if(versionInfo()$version < "1.3.1056"){
	parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}  
}

#temp_name <- '_temp_gdal_outs'
#temp_dir <- paste(getwd(), temp_name, sep = '/') # directory for temporary files

```


## 1 get raster data
```{r}
raster_file <- file.path('../data/WUI-selected/landcover.tif')

# system.time(lc_stars  <- stars::read_stars(raster_file, proxy = TRUE))
# 
# (pxl_conv <- .75*.75) 
# 
# plot(lc_stars)
```


## 2 buffer buildings very slightly
```{r}
# '1' = 'tree', 
# '2' = 'grass',
# '3' = 'soil',
# '4' = 'water',
# '5' = 'building',
# '6' = 'road',
# '7' = 'other_paved',
# '8' = 'shrub'



```


## 3 summarize distance rasters within building donuts
```{r}

```
