---
title: "03_descriptives_EDA"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This assumes "02_Woosley_combine_data.Rmd" was run


## 0 set up: load libraries, custom functions, set defaults
```{r}
# load libraries
# packages we'll be using
packs <- c('tidyverse'        # a must have!
           , 'tidylog'        # makes things very verbose for 2x checking 
           , 'magrittr'       # all of the pipes
           , 'janitor'        # cleans things up
           , 'sf'             # simple features
           , 'mapview'        # quick webmaps for zoom/pan viz
           , 'gtsummary'      # for descriptive table
           , 'patchwork'
           #'tidycensus',     # access to Census data in a tidy way 
           #'party',          # random forests
           , 'dataMaid'       # nice reports
           , 'patchwork'      # combine ggplot graphics
           , 'tictoc'         # times things
           , 'beepr'          # makes noises
           , 'psych'          # describe is very useful for descriptive statistics
           , 'sjPlot'
           ,'sciplot')        # useful plotting and regression support

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

lapply(packs, library, character.only = TRUE)


# changing from tidyr v0.8.3 -> v1.0.0 broke things for nest and unnest!
# https://tidyr.tidyverse.org/articles/in-packages.html#tidyr-v0-8-3---v1-0-0
library(tidyr)
nest <- nest_legacy                     # Why Hadley, WHY!
unnest <- unnest_legacy


# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
names(.) %>% as.character(.)       # my simple features
}

see_sf() -> sf_in_memory

## what are the spatial references of those SF classes?
mget(sf_in_memory) %>%
purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()

# NOT IN
`%nin%` <- Negate(`%in%`) # custom function

# where are we?
list.files()
list.files('data')

# parameter to keep in general, for later..
pxl_to_ft_conversion <- 0.75
# pxl_to_ft_conversion <- 0.2286004572

set.seed(19870630)

## Make a 'figures' subdirectory if one doesn't exist
# ifelse(!dir.exists(file.path('figures')), dir.create(file.path('figures')), FALSE)
```


## 1 read in the data
```{r}
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-04-07.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-04-15.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-04-23.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-04-26.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-09-27.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-10-05.csv')) %>% glimpse
#build <- read_csv(paste0(getwd(), '/output_data/building_2021-11-03.csv')) %>% glimpse
#build <- read_csv(paste0(getwd(), '/output_data/building_2021-12-02.csv')) %>% glimpse
# build <- read_csv(paste0(getwd(), '/output_data/building_2021-12-22.csv')) %>% glimpse
build <- read_csv(paste0(getwd(), '/output_data/building_2022-02-01.csv')) %>% glimpse



 
```


## 2 descriptive statistics & table for pub
```{r eval=FALSE, include=FALSE}

# generates report of univariate distributions with added info
system.time(makeDataReport(build, file = paste0(getwd(), '/output_data/dataMaid_',
                                    gsub('[[:punct:]]', '_', Sys.time()), '.Rmd')))


# univariate descriptions
build %>% 
  #tidylog::select_if(is_double) %>% 
  describe %>% 
  data.frame() %>% 
  rownames_to_column(var = 'variable_name') %>% 
  rename(variable_number = vars)  %>% 
  # write_csv(., paste0(getwd(), '/output_data/describe_',
  #                   gsub('[[:punct:]]', '_', Sys.time()), '.csv'))

# Remember re sample size w RF, we should include parcel_year_built and build_Mean_distroad 
#some additional descriptive information/summaries
length(unique(build$ID_Parcel)) #number of unique parcels
table(build$damage_cat)
table(build$build_structures_DAMAGE)
tabyl(build$build_PROPANETAN)

#DINS has 12% survived only
table(build$damage_binary,build$build_DINS)

#type of parcel, 9983 were residential
table(build$parcel_UseType)
#homeowner occupied
table(build$parcel_Roll_HomeOwnersExemp); #5600 or 7000 indicates homeowner occupied - see https://www.titleadvantage.com/mdocs/Homeowners%20prop%20tax%20exemption%20all.pdf
table(build$parcel_UseType,build$parcel_Roll_HomeOwnersExemp) #Among residential, Residential 44.3% are owner occupied, and 54.9% renter occupied
  
# # confirming it's ok to have low values for build_perc_overhang and build_overhang_ht when build_has_tree_overhang is 1
# build %>% 
#   select(damage_binary, build_has_tree_overhang, build_perc_overhang, build_overhang_ht) %>%  
#   mutate(build_perc_overhang = build_perc_overhang*100) %>%
#     filter(build_has_tree_overhang == '1') %>% view()


#Summary tables on defensible space - descriptive summary for pub
# notes as of 3/23/2022 - will share table with coauthors - not sure if we want mean/sd or median IQR; if we want by outcome or not

# part 1 - builds a table about defensible space and building and parcel area
build %>% 
  select(damage_binary, parcel_area, build_area, build_min_dist_tree, build_near_build, build_min_dist_shrub, build_has_tree_overhang, ) %>%  # cols of interest
  tbl_summary(#by =damage_binary,                                     # create summary table, can turn on or off by damage
     digits = all_continuous() ~ 1,
     type = all_continuous() ~ "continuous2",       # indicate that you want to print multiple statistics 
     statistic = list(all_continuous() ~ c("{mean} ({sd})",                            #line 1: mean and SD
                                          "{median} ({p25}, {p75})",                   # line 2: median IQR
                                          "{min}-{max}"),                              # line 3: min and max
         all_categorical() ~ c("{n} / {N} ({p}%)")),
      label  = list(                                              # display labels for column names
          damage_binary   ~ "Building Destroyed"),
        missing_text = "Missing"  )->t1


# part 2 - for those buildings with tree overhang, summary of percent overhang and height
build %>% 
  select(damage_binary, build_has_tree_overhang, build_perc_overhang, build_overhang_ht) %>%  
  mutate(build_perc_overhang = build_perc_overhang*100) %>%
    filter(build_has_tree_overhang == '1') %>%  
        tbl_summary(#by =damage_binary, # create summary table, can turn on or off by damage
            digits = all_continuous() ~ 1,
            type = all_continuous() ~ "continuous2",       # indicate that you want to print multiple statistics 
            statistic = list(all_continuous() ~ c("{mean} ({sd})",                            #line 1: mean and SD
                                          "{median} ({p25}, {p75})",                   # line 2: median IQR
                                          "{min}-{max}"),                              # line 3: min and max
            all_categorical() ~ c("{n} / {N} ({p}%)")),
      label  = list(                                              # display labels for column names
          damage_binary   ~ "Building Destroyed"),
        missing_text = "Missing"  )->t2

tbl_desc <- tbl_stack(list(t1, t2))  #combines tables
    

tbl_desc %>% #exports as csv
      gtsummary::as_tibble()  %>% 
          write_csv(., paste0(getwd(), '/data/Table_Descript_', Sys.Date(), '.csv'))
  
tbl_desc %>% #exports as image
      as_gt() %>%             # convert to gt table
           gt::gtsave(., paste0(getwd(), '/figures/Table_Descript_' , Sys.Date(), '.png'))



```


## 3 correlations
```{r}

# TODO check out error message.
build %>%
  tidylog::select_if(is_double) %>% # just numerically-encoded variables
  tab_corr(.
           , triangle = 'lower'
           # , file = paste0(getwd(), '/output_data/correlations_',
           #                 gsub('[[:punct:]]', '_', Sys.time()), '.html')
           )


# find large correlations
build %>% 
  tidylog::select_if(is_double) %>% 
  cor() %>% 
  data.frame() %>% 
  rownames_to_column() %>% 
  as_tibble() %>%
  pivot_longer(-rowname) %>% 
  arrange(desc(value)) -> cors_tibble

#select any pairs where correlation coefficient greater .7
#all the pairs with corr greater than .7 are either duplicate measures of vegetation at differences or parcel chars
cors_tibble %>% 
  filter(value > .7 & value < 1) %>% 
    View()


#Older thoughts on correlations
#near_dest and near_exp highly correlated, not surprising
 #elevation measures are highly correlated, not surprising
 #elevation of a building is related to land cover (higher elev has less road and building around but more veg- relationships differ w 10 vs 200 buffer)
 #build_min_dist_shrub correlated w elevation - wouldn't have thought that.
 #build_dist_angle-from near tool, angle to nearest building
 #tree overhang measures and 10 m are all pretty related
 #none of these are very strong corrs - but building age is related to landscape characteristics - older buildings are higher elev, farther from road, closer to shrub,have more tree overhang and more tree around building (less grass, less imperv). Older buildings are on parcels that have more tree and pervious cover, but less grass & building cover


```


## 4 missing values
```{r}
build %>% map(., ~sum(is.na(.))) # TODO drop missings fit, models and see if variables with missing values 'matter' in the prediction of burn

build %>%
  map(., ~sum(is.na(.))) %>%
  map_dfc(., ~.x) %>% 
  t() %>% 
  View()
```



# 5 hists land cover & draft for pub
```{r}

build %>% 
  #st_drop_geometry() %>% 
  tidylog::select(ID_Build, contains('build_p_')) %>% 
  pivot_longer(-ID_Build) %>% 
  mutate(#buff_dist = as.numeric(str_remove_all(name, '\\D')),
         var = str_remove(name, 'build_p_')) %>% 
  separate(var, into = c('var', 'buff_dist'), sep = '_', convert = TRUE) %>% 
  ggplot(aes(x = value)) + 
  # geom_density() + 
  geom_histogram() +
  #facet_wrap(~var + buff_dist, ncol = 4) +
  facet_grid(buff_dist ~ var) +
  theme_bw() + 
  # ggsave(file = paste0(getwd(), '/figures/donut_buff_landcover_',
  #                   gsub('[[:punct:]]', '_', Sys.time()), '.png')) +
  NULL

#work on for publication, only 300 m
# 4/6/2022
#if we keep, reorder factors, and tweak formatting
ggp4<- build %>% 
  #st_drop_geometry() %>% 
  tidylog::select(ID_Build, contains('build_p_')) %>% 
  pivot_longer(-ID_Build) %>% 
  mutate(#buff_dist = as.numeric(str_remove_all(name, '\\D')),
         var = str_remove(name, 'build_p_')) %>% 
  separate(var, into = c('var', 'buff_dist'), sep = '_', convert = TRUE) %>%  #if we keep, reorder factors, and tweak formatting
  filter(buff_dist == 300 & var != 'water')%>% 
  ggplot(aes(x = value, fill = var)) +  
  geom_histogram() +
  facet_wrap(~var, ncol=4)+
  theme_bw() + labs(title = "Histogram of land cover (300 ft) around building")+ 
  # ggsave(file = paste0(getwd(), '/figures/buff_landcover_300',
  #                   gsub('[[:punct:]]', '_', Sys.time()), '.png')) +
  # NULL

#work on for publication, 
# 4/6/2022  


ggp1<- build %>% ggplot(aes(build_Mean_elev_100m)) + geom_histogram(binwidth = 25) + theme_classic()
ggp2<- build %>% ggplot(aes(build_Mean_distroad)) + geom_histogram(binwidth = 20)+ theme_classic()
ggp3<- build %>% ggplot(aes(build_Mean_builddens)) + geom_histogram(binwidth = .1)+ theme_classic()
ggp_all <- (ggp1 + ggp2) / (ggp3 + ggp4) +    # Create grid of plots with title
  plot_annotation(title = "Descriptives for publication") & 
  theme(plot.title = element_text(hjust = 0.5))
ggp_all   




```


## 6 year built
```{r}
build %>%   #Dexter, this & below don't run for me, FWIW
  tidylog::select(starts_with("parcel_Effective"),
         # starts_with("parcel_YearBuilt"),
         parcel_year_built) %>% map(., ~sum(is.na(.)))

# how many of these 
build %>%
  filter(parcel_Roll_ImpValue == 0 &
           parcel_Roll_HomeOwnersExemp == 0 &
           parcel_Build_P == 0) %>% # year built should be zero for these
  glimpse()

# where are these NA's?
build %>% filter(is.na(parcel_year_built)) #%>% mapview()
build %>% filter(parcel_year_built == 0) #%>% mapview()

summary(build$parcel_year_built)

build %>%
  ggplot(aes(parcel_year_built)) +
  geom_histogram() -> build_year_built_hist

build %>%
  filter(parcel_year_built > 0) %>% 
  ggplot(aes(parcel_year_built)) +
  geom_histogram() + 
  ggtitle('zeros removed') -> build_year_built_hist_no_zero

build_year_built_hist + build_year_built_hist_no_zero

# ggsave(file = paste0(getwd(), '/figures/effective_yearRecent_',
#                     gsub('[[:punct:]]', '_', Sys.time()), '.png'))
```


## 7 land use
```{r}

(build %>% tabyl(parcel_UseDescription) %>% as_tibble() -> lu_counts)


lu_counts %>%
  ggplot(aes(n, reorder(parcel_UseDescription, -n))) + 
  geom_col() + 
  theme_bw() + 
  NULL
  

```


## 8 boxplots w/predictors
```{r}

#  
# DINS work
#DINS has 12% survived only
table(build$damage_binary,build$build_DINS)

#roof siding veg - these look like interesting relationships
par(mfrow=c(1,3))
bargraph.CI(build$build_ROOFCONSTR,build$damage_binary,main="Roof",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_EXTERIORSI,build$damage_binary,main="Ext Siding",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_VEGCLEARAN,build$damage_binary,main="Veg clear",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))

par(mfrow=c(3,3))
bargraph.CI(build$build_FENCEATTAC,build$damage_binary,main="Fence",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_DECKPORCHO,build$damage_binary,main="Deck/Porch Ongrade",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_DECKPORCHE,build$damage_binary,main="Deck/Porch Elev",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_ROOFCONSTR,build$damage_binary,main="Roof",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_PROPANETAN,build$damage_binary,main="Propane",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_WINDOWPANE,build$damage_binary,main="Window",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_EAVES,build$damage_binary,main="Eaves",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1))
bargraph.CI(build$build_VENTSCREEN,build$damage_binary,main="Ventscreen",ylab="P(Loss)",xlab="",las=2,ylim=c(0,1)) 
  

box_plot_dat <- build %>%
  dplyr::select(damage_binary | where(is.double)) %>% 
  dplyr::select(c(damage_binary:build_near_exp)) %>%  #this might need to be revised if build variables change
  data.frame()
 
# 
# for(i in 2:ncol(box_plot_dat)){
#   print(names(box_plot_dat)[i])
#   png(file = paste0(getwd(), '/figures/boxplot_', names(box_plot_dat)[i], '_',
#                     gsub('[[:punct:]]', '_', Sys.time()), '.png'))
#   boxplot(box_plot_dat[,i] ~ box_plot_dat$damage_binary, main = names(box_plot_dat)[i])
#   dev.off()
# }

# renters vs. owners -doesn't seem to make a difference in outcome #Roll_HomeOwnersExemp==0 are renters, 5600 & 7000 are owners; 
# filter first by parcel_UseType=Residential

build %>%
  tidylog::filter(parcel_UseType=='Residential')  %>%
    tabyl(damage_binary,parcel_Roll_HomeOwnersExemp)%>%
      adorn_percentages() 


# summary(lm(damage_binary ~ build_near_dest, build))
# summary(lm(damage_binary ~ build_near_exp, build))




 
 ```


TODO expand EDA? Others?




```{r, citations}
lapply(packs, citation)
```


Last knit on `r format(Sys.time())`


```{r}
system.time(save.image(file = paste0('saved_sessions/wui_r_desc_eda_', gsub('[[:punct:]]', '-', Sys.time()), '.RData')))
```

