---
title: "05_DINS"
author: "Dexter H. Locke, PhD"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## 0 set up: load libraries, custom functions, set defaults
```{r}
# load libraries
# packages we'll be using
packs <- c('tidyverse'        # a must have!
           , 'tidylog'        # makes things very verbose for 2x checking 
           , 'magrittr'       # all of the pipes
           , 'janitor'        # cleans things up
           , 'sf'             # simple features
           , 'mapview'        # quick webmaps for zoom/pan viz
           #'tidycensus',     # access to Census data in a tidy way 
           #'party',          # random forests
           , 'tictoc'         # times things
           , 'beepr'          # makes noises
           , 'psych'          # describe is very useful for descriptive statistics
           , 'sjPlot')        # useful plotting and regression support

# check for all of the libraries
if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))  
}

lapply(packs, library, character.only = TRUE)


# changing from tidyr v0.8.3 -> v1.0.0 broke things for nest and unnest!
# https://tidyr.tidyverse.org/articles/in-packages.html#tidyr-v0-8-3---v1-0-0
library(tidyr)
nest <- nest_legacy                     # Why Hadley, WHY!
unnest <- unnest_legacy


# set custom function for getting spatial data
see_sf <- function(){
# what's in memory that are sf - spatial features?
keep(eapply(.GlobalEnv, class),      # gets the objects in the global environment
     ~ any(str_detect(., "sf"))) %>% # selects elements with sf in them
names(.) %>% as.character(.)       # my simple features
}

see_sf() -> sf_in_memory

## what are the spatial references of those SF classes?
mget(sf_in_memory) %>%
purrr::map(~st_crs(.x)$epsg) %>% unlist() #%>% View()

# NOT IN
`%nin%` <- Negate(`%in%`) # custom function

# where are we?
list.files()
list.files('data')

# parameter to keep in general, for later..
pxl_to_ft_conversion <- 0.75
# pxl_to_ft_conversion <- 0.2286004572

set.seed(19870630)

## Make a 'figures' subdirectory if one doesn't exist
# ifelse(!dir.exists(file.path('figures')), dir.create(file.path('figures')), FALSE)
```


## 1 bring in new GIS data from Miranda, this will be the base from now on (August, 2020)
```{r}
# GIS DATA from MIRANDA
st_layers(paste0(getwd(), '/data/Outgoing_BuildingSumms_DHL20200423.gdb'))


dins <- read_sf(dsn = paste0(getwd(), '/data/Outgoing_BuildingSumms_DHL20200423.gdb'),
                      layer = 'Buildings_ParcelID_DINS',
                      quiet = FALSE) 

glimpse(dins)
```


## 2 reclass DINS
```{r}

# Past Syphard et al papers had roof, exterior, window pane, window frame
# More recent ones include wider range of information in DINS

dins %>% 
  st_drop_geometry() %>% names()

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% View()

#TO DO variables to include? - Dexter, these all seem to have ok data, but need some reclassing/your thoughts on models.
#1. exterior siding materials 
#2. fence materials
#3. deck/porch materials
#4. roof materials
#5. patio/cover materials
#6. propane tank distance
#7. window panes

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_EXTERIORSI) #exterior siding, have data for 75% of sample; categories ok

dins %>%
st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% 
   tabyl(Buildings_ParcelID_DINS_intersects_FENCEATTAC) #fence materials, have data for 70% of sample, although 50% had no fence; reclass no fence to N/A?

dins %>% 
 st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
 tabyl(Buildings_ParcelID_DINS_intersects_DECKPORCHO) #deck and porch materials, have data for 65% of sample; should change 'no deck/porch' to N/A? 

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_ROOFCONSTR) #roof, have data for 65% sample, should drop 'other' bc only 8 observations

 dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>% 
  tabyl(Buildings_ParcelID_DINS_intersects_PATIOCOVER) # materials on covered patio or carport, have data for 65% of sample although 44% have no carport or patio cover; reclass 'no' to N/A
 
 
 dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_EXTERIORSI,Buildings_ParcelID_DINS_intersects_PATIOCOVER) %>% adorn_totals()

dins %>% 
 st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_PROPANETAN) #propane tank, has data for 56% of sample; reclass categories so blank is unknown and others are in order, N/A = no   tank

dins %>% 
  st_drop_geometry() %>% 
  filter(!is.na(Buildings_ParcelID_DINS_intersects_INCIDENTST)) %>%
  tabyl(Buildings_ParcelID_DINS_intersects_WINDOWPANE) #windowpane, have data for 40% of sample, categories ok

  
# also in DINS, but don't bother with? bc sample sizes are so low:
  #tabyl(Buildings_ParcelID_DINS_intersects_DEFENSIVEA) #defensive actions, I think data for ~40% but don't know if blank is a no or an unknown
  #tabyl(Buildings_ParcelID_DINS_intersects_EAVES) #eaves, has data for ~33% only.  
  #tabyl(Buildings_ParcelID_DINS_intersects_VENTSCREEN) #only data on 29% of sample, and 11% of sample had no vents.
                 

```





```{r, citations}
lapply(packages, citation)
```


Last knit on `r format(Sys.time())`


```{r}
system.time(save.image(file = paste0('saved_sessions/wui_r_DINS_',
                                     gsub('[[:punct:]]', '-', Sys.time()), '.RData')))
```

